# Generated by Django 5.1.1 on 2024-10-09 04:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_de_consulta', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Sugerencia'), (2, 'Reclamos')])),
                ('mensaje', models.TextField()),
                ('aviso', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='profesional_id',
        ),
        migrations.AddField(
            model_name='turnos',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='turnos',
            name='eliminado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cancelado'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='turnos',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profesional', verbose_name='Medico'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.obra_social'),
        ),
    ]
