# Generated by Django 5.1.2 on 2024-10-15 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contacto_remove_turnos_profesional_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.especialidad'),
        ),
    ]
